### ISSUE TITLE
Zoom to selection fails with: Cannot read property 'unbind' of null

### ISSUE THREAD

**Issue by alexkiro** [ogorlab/ogor-frontend#105]
For certain users the zoom to selection fails with this weird error for some reason:

```
TypeError: Cannot read property 'unbind' of null
  at s7(/maps-api-v3/api/js/41/3a/drawing_impl.js:2:352)
  at p7._.t.Mg(/maps-api-v3/api/js/41/3a/drawing_impl.js:16:297)
  at F7(/maps-api-v3/api/js/41/3a/drawing_impl.js:11:490)
  at _.sK.<anonymous>(/maps-api-v3/api/js/41/3a/drawing_impl.js:10:72)
  at Vd.H(/maps/api/js:199:294)
  at Object._.N.trigger(/maps/api/js:196:157)
  at Object.Qd(/maps-api-v3/api/js/41/3a/util.js:211:284)
  at Zo.Jb(/maps-api-v3/api/js/41/3a/common.js:149:240)
  at Ro._.t.Jb(/maps-api-v3/api/js/41/3a/common.js:146:175)
  at HTMLDocument.ka._.cp.Qb(/maps-api-v3/api/js/41/3a/common.js:65:287)
  at HTMLDocument.r(/js/sentry.31b6d13e.js:1:38498)
```

Which seems to be a strange error from the GMapsJS API. :thinking: 

--

cc @dafinajeaca

**Comment by alexkiro** [comment]
Confirmed fixed with @dafinajeaca
